<div class="addContainer">
    <?php if ($this->flashMessenger()->hasCurrentSuccessMessages()): ?>
    <div class="alert alert-success text-center" role="alert">
        <?php
        echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><h1>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</h1></div>')
            ->render('success');
        $this->flashMessenger()->clearMessages();
        ?>
    </div>
    <?php endif ?>

<!--    --><?php //if ($this->wasEdited): ?>
<!--        <div class="alert alert-success text-center" role="alert">-->
<!--            <h1>Обновлено успешно</h1>-->
<!--        </div>-->
<!--    --><?php //else: ?>
<!---->
<!--    --><?php //endif ?>
    <h1 class="text-center reg-album-header">Редактировать альбом</h1>
    <?php
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
    ?>
    <div class="mb-3">
        <?= $this->formRow($this->form->get('album')->get('name')); ?>
    </div>
    <div class="mb-3">
        <?= $this->formRow($this->form->get('album')->get('description')); ?>
    </div>
    <div class="mb-3">
        <?= $this->formRow($this->form->get('album')->get('photographer')); ?>
    </div>
    <div class="mb-3">
        <?= $this->formRow($this->form->get('album')->get('email')); ?>
    </div>
    <div class="mb-3">
        <?= $this->formRow($this->form->get('album')->get('phone')); ?>
    </div>

    <div class='w-100 d-flex justify-content-center mt-8'>
        <?= $this->formSubmit($this->form->get('album')->get('submit')); ?>
    </div>

    <?= $this->form()->closeTag($this->form); ?>

    <div class='w-100 d-flex justify-content-center mt-8'>
        <a class='btn btn-primary' href="/">Вернуться на главную</a>
    </div>

</div>
