<h1>Image Gallery</h1>

<p>
    Эта страница отображает список выгруженных изображений.
</p>

<p>
    <a href="<?= $this->url('images', ['action' => 'upload', 'albumId' => $albumId]); ?>"
       class="btn btn-primary" role="button">Добавить фотографию</a>
</p>

<p>
    <a href="<?= $this->url('home'); ?>"
       class="btn btn-primary" role="button">Главная</a>
</p>

<hr/>

<?php if (count($files) == 0): ?>

    <p>
        <i>Нет файлов для отображения.</i>
    </p>

<?php else: ?>

    <div class="row">
        <div class="col-sm-6 col-md-12">
            <div class="img-thumbnail">
                <?php foreach ($files as $file): ?>

                    <a target="_blank" href=<?= "/uploads/$albumId/$file" ?>>
                        <img
                                src='<?= "/uploads/$albumId/min/$file" ?>'
                                alt="Не найдено"
                        >
                    </a>
<!--                    <a target="_blank" href=-->
<!--                    --><?//= "/images/file/$albumId?name=$file" ?>
<!--                    >-->
<!--                        <img-->
<!--                                src='-->
<!--                                --><?//= "/uploads/$albumId/min/$file" ?>
<!--                                '-->
<!--                                alt="Не найдено"-->
<!--                        >-->
<!--                    </a>-->

                    <div class="caption">
                        <h3><?php echo $file; ?></h3>
                        <p>
                            <a href="<?= $this->url('deletePhoto', ['albumId' => $albumId],
                                ['query' => ['photoName' => $file]]); ?>"
                               class="btn btn-default" role="button">Удалить</a>
                        </p>
                    </div>

                <?php endforeach; ?>
            </div>

        </div>
    </div>

<?php endif; ?>

<hr/>