<?php
if ($this->flashMessenger()->hasCurrentSuccessMessages()): ?>
    <div class="alert alert-success text-center" role="alert">
        <?php echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><h1>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</h1></div>')
            ->render('success'); ?>
    </div>
<?php endif ?>

<?php
foreach ($this->albums as $album):
    ?>

    <div class="album-unit">
<!--        <img src="-->
<!--        --><?php //echo $this->url(
//            'images',
//            ['action' => 'file', 'albumId' => $album->getId()],
//            ['query' => ['getLast' => true]])
//        ?><!--"-->
<!--             alt=""-->
<!--        >-->

        <img src="<?= $this->url(
            'images',
            ['action' => 'file', 'albumId' => $album->getId()], ['query' => ['thumbnail' => true]]) ?>" alt="">
        <p><a href="<?= $this->url('edit', ['albumId' => $album->getId()]); ?>">Название: <?= $album->getName() ?></a>
        </p>
        <p>Описание: <?= $album->getDescription() ?></p>
        <p>Фотограф: <?= $album->getPhotographer() ?></p>
        <?php if ($album->getEmail() !== ''): ?>
            <p>Почта: <?= $album->getEmail() ?></p>
        <?php endif ?>
        <?php if ($album->getPhone() !== ''): ?>
            <p>Телефон: <?= $album->getPhone() ?></p>
        <?php endif ?>

        <p>
            <a href="<?= $this->url('images', ['albumId' => $album->getId()]); ?>"
               class="btn btn-primary" role="button">Посмотреть фотографии</a>
        </p>
        <p>
            <a href="<?= $this->url('edit', ['albumId' => $album->getId()]); ?>"
               class="btn btn-primary" role="button">Редактировать альбом</a>
        </p>
        <p>
            <a href="<?= $this->url('deleteAlbum', ['albumId' => $album->getId()]); ?>"
               class="btn btn-primary" role="button">Удалить альбом</a>
        </p>
    </div>


<?php
endforeach;
?>
