<?php
if ($this->flashMessenger()->hasCurrentSuccessMessages()): ?>
    <div class="alert alert-success text-center" role="alert">
        <?php echo $this->flashMessenger()
            ->setMessageOpenFormat('<div%s><h1>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</h1></div>')
            ->render('success'); ?>
    </div>
<?php endif ?>

<?php
foreach ($this->albums as $album):
    ?>

    <div class="album-unit">
        <p><a href="<?= $this->url('edit', ['albumId' => $album->getId()]); ?>">Название: <?= $album->getName() ?></a>
        </p>
        <p>Описание: <?= $album->getDescription() ?></p>
        <p>Фотограф: <?= $album->getPhotographer() ?></p>
        <?php if ($album->getEmail() !== ''): ?>
            <p>Почта: <?= $album->getEmail() ?></p>
        <?php endif ?>
        <?php if ($album->getPhone() !== ''): ?>
            <p>Телефон: <?= $album->getPhone() ?></p>
        <?php endif ?>

        <p>
            <a href="<?= $this->url('images', ['albumId' => $album->getId()]); ?>"
               class="btn btn-primary" role="button">Посмотреть фотографии</a>
        </p>
    </div>


<?php
endforeach;
?>
